import type { ActivityEvent, Beneficiary, JourneyStage } from "./types";

export const PROGRAMS = [
  "Education Access",
  "Community Health",
  "Clean Water Program",
  "Emergency Relief",
  "Youth Development",
  "Food Distribution",
];

export const SUPPORT_TYPES = [
  "Education Support",
  "Healthcare Outreach",
  "Clean Water",
  "Food Assistance",
  "Community Support",
  "Emergency Relief",
];

export const REGIONS = [
  "Northern Virginia",
  "Central Appalachia",
  "Gulf Coast",
  "Pacific Northwest",
  "Midwest Urban",
  "Southwest Border",
];

export const JOURNEY_STAGES: JourneyStage[] = [
  "Enrolled",
  "Needs Assessed",
  "Support Assigned",
  "Service Active",
  "Outcome Review",
  "Follow-Up",
];

export const COORDINATORS = [
  "Maria Santos",
  "James Okonkwo",
  "Priya Sharma",
  "Daniel Brooks",
  "Elena Vasquez",
];

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: "ben-001",
    beneficiaryId: "BNF-2026-0142",
    name: "Amina Hassan",
    location: "Alexandria, VA",
    region: "Northern Virginia",
    program: "Education Access",
    supportType: "Education Support",
    status: "Active",
    journeyStage: "Service Active",
    followUpStatus: "Scheduled",
    coordinator: "Maria Santos",
    enrollmentDate: "2026-01-15",
    lastSupportDate: "2026-07-18",
    nextFollowUp: "2026-08-05",
    outcomeStatus: "In Progress",
    notes: "Receiving tutoring and school supplies support.",
  },
  {
    id: "ben-002",
    beneficiaryId: "BNF-2026-0087",
    name: "Carlos Mendez",
    location: "Charleston, WV",
    region: "Central Appalachia",
    program: "Community Health",
    supportType: "Healthcare Outreach",
    status: "Follow-Up Required",
    journeyStage: "Follow-Up",
    followUpStatus: "Overdue",
    coordinator: "James Okonkwo",
    enrollmentDate: "2025-11-02",
    lastSupportDate: "2026-06-22",
    nextFollowUp: "2026-07-10",
    outcomeStatus: "Review Due",
    notes: "Mobile clinic follow-up overdue after initial screening.",
  },
  {
    id: "ben-003",
    beneficiaryId: "BNF-2026-0201",
    name: "The Nguyen Family",
    location: "Houston, TX",
    region: "Gulf Coast",
    program: "Food Distribution",
    supportType: "Food Assistance",
    status: "Active",
    journeyStage: "Service Active",
    followUpStatus: "None",
    coordinator: "Priya Sharma",
    enrollmentDate: "2026-03-08",
    lastSupportDate: "2026-07-20",
    nextFollowUp: "",
    outcomeStatus: "Positive",
    notes: "Household receiving weekly food assistance packages.",
  },
  {
    id: "ben-004",
    beneficiaryId: "BNF-2026-0033",
    name: "Eleanor Price",
    location: "Portland, OR",
    region: "Pacific Northwest",
    program: "Clean Water Program",
    supportType: "Clean Water",
    status: "Under Review",
    journeyStage: "Outcome Review",
    followUpStatus: "Required",
    coordinator: "Daniel Brooks",
    enrollmentDate: "2025-09-14",
    lastSupportDate: "2026-07-05",
    nextFollowUp: "2026-07-28",
    outcomeStatus: "Review Due",
    notes: "Water filtration system installed; outcome review pending.",
  },
  {
    id: "ben-005",
    beneficiaryId: "BNF-2026-0178",
    name: "Marcus Johnson",
    location: "Detroit, MI",
    region: "Midwest Urban",
    program: "Youth Development",
    supportType: "Community Support",
    status: "Active",
    journeyStage: "Service Active",
    followUpStatus: "Scheduled",
    coordinator: "Elena Vasquez",
    enrollmentDate: "2026-02-20",
    lastSupportDate: "2026-07-19",
    nextFollowUp: "2026-08-12",
    outcomeStatus: "In Progress",
    notes: "Youth mentorship and after-school programming.",
  },
  {
    id: "ben-006",
    beneficiaryId: "BNF-2026-0056",
    name: "Sofia Ramirez",
    location: "El Paso, TX",
    region: "Southwest Border",
    program: "Emergency Relief",
    supportType: "Emergency Relief",
    status: "Enrolled",
    journeyStage: "Needs Assessed",
    followUpStatus: "Required",
    coordinator: "Maria Santos",
    enrollmentDate: "2026-07-12",
    lastSupportDate: "2026-07-14",
    nextFollowUp: "2026-07-25",
    outcomeStatus: "Pending",
    notes: "Recently enrolled after displacement event.",
  },
  {
    id: "ben-007",
    beneficiaryId: "BNF-2025-0440",
    name: "David Chen",
    location: "Arlington, VA",
    region: "Northern Virginia",
    program: "Community Health",
    supportType: "Healthcare Outreach",
    status: "Completed",
    journeyStage: "Follow-Up",
    followUpStatus: "Completed",
    coordinator: "James Okonkwo",
    enrollmentDate: "2025-06-01",
    lastSupportDate: "2026-05-30",
    nextFollowUp: "",
    outcomeStatus: "Positive",
    notes: "Completed preventive care cycle with positive outcomes.",
  },
  {
    id: "ben-008",
    beneficiaryId: "BNF-2026-0119",
    name: "Grace Okafor",
    location: "New Orleans, LA",
    region: "Gulf Coast",
    program: "Education Access",
    supportType: "Education Support",
    status: "Active",
    journeyStage: "Support Assigned",
    followUpStatus: "None",
    coordinator: "Priya Sharma",
    enrollmentDate: "2026-04-03",
    lastSupportDate: "2026-07-17",
    nextFollowUp: "2026-08-20",
    outcomeStatus: "In Progress",
    notes: "Scholarship and literacy program participant.",
  },
];

export const INITIAL_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-001",
    beneficiaryId: "ben-006",
    beneficiaryName: "Sofia Ramirez",
    type: "Beneficiary Enrolled",
    detail: "Emergency relief enrollment completed for Southwest Border region.",
    createdAt: "2026-07-12T14:30:00",
  },
  {
    id: "act-002",
    beneficiaryId: "ben-003",
    beneficiaryName: "The Nguyen Family",
    type: "Support Delivered",
    detail: "Weekly food assistance package delivered in Gulf Coast region.",
    createdAt: "2026-07-20T09:15:00",
  },
  {
    id: "act-003",
    beneficiaryId: "ben-002",
    beneficiaryName: "Carlos Mendez",
    type: "Status Updated",
    detail: "Follow-up marked overdue — coordinator review required.",
    createdAt: "2026-07-19T16:45:00",
  },
  {
    id: "act-004",
    beneficiaryId: "ben-007",
    beneficiaryName: "David Chen",
    type: "Outcome Updated",
    detail: "Positive outcome recorded after preventive care completion.",
    createdAt: "2026-07-18T11:20:00",
  },
  {
    id: "act-005",
    beneficiaryId: "ben-005",
    beneficiaryName: "Marcus Johnson",
    type: "Service Assigned",
    detail: "Youth mentorship services assigned through Youth Development program.",
    createdAt: "2026-07-17T13:00:00",
  },
];
