import type {
  PermissionRole,
  Team,
  TeamActivityEvent,
  TeamAssignment,
  TeamDiscussion,
  TeamMeeting,
  TeamMember,
} from "./types";

export const DEPARTMENTS = [
  "Programs & Impact",
  "Community Outreach",
  "Fundraising & Partnerships",
  "Operations",
  "Finance & Compliance",
  "Leadership",
];

export const ROLES = [
  "Administrator",
  "Executive Director",
  "Program Manager",
  "Team Lead",
  "Finance",
  "Field Staff",
  "Coordinator",
  "Viewer",
];

export const PERMISSION_LABELS = [
  "View",
  "Create",
  "Edit",
  "Approve",
  "Manage Members",
  "Manage Financial Data",
  "Manage Permissions",
];

export const PERMISSION_ROLES: PermissionRole[] = [
  {
    id: "admin",
    name: "Administrator",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: true,
      "Manage Members": true,
      "Manage Financial Data": true,
      "Manage Permissions": true,
    },
  },
  {
    id: "exec",
    name: "Executive Director",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: true,
      "Manage Members": true,
      "Manage Financial Data": true,
      "Manage Permissions": false,
    },
  },
  {
    id: "pm",
    name: "Program Manager",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: true,
      "Manage Members": true,
      "Manage Financial Data": false,
      "Manage Permissions": false,
    },
  },
  {
    id: "lead",
    name: "Team Lead",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: false,
      "Manage Members": true,
      "Manage Financial Data": false,
      "Manage Permissions": false,
    },
  },
  {
    id: "finance",
    name: "Finance",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: true,
      "Manage Members": false,
      "Manage Financial Data": true,
      "Manage Permissions": false,
    },
  },
  {
    id: "field",
    name: "Field Staff",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: false,
      "Manage Members": false,
      "Manage Financial Data": false,
      "Manage Permissions": false,
    },
  },
  {
    id: "coord",
    name: "Coordinator",
    permissions: {
      View: true,
      Create: true,
      Edit: true,
      Approve: false,
      "Manage Members": false,
      "Manage Financial Data": false,
      "Manage Permissions": false,
    },
  },
  {
    id: "viewer",
    name: "Viewer",
    permissions: {
      View: true,
      Create: false,
      Edit: false,
      Approve: false,
      "Manage Members": false,
      "Manage Financial Data": false,
      "Manage Permissions": false,
    },
  },
];

export const INITIAL_MEMBERS: TeamMember[] = [
  {
    id: "mem-001",
    name: "Maya Patel",
    email: "maya.patel@hopebridge.org",
    phone: "+1 (703) 555-0142",
    role: "Program Manager",
    department: "Programs & Impact",
    teamIds: ["team-001"],
    assignmentCount: 5,
    workload: 76,
    availability: "Focused",
  },
  {
    id: "mem-002",
    name: "Daniel Brooks",
    email: "daniel.brooks@hopebridge.org",
    role: "Team Lead",
    department: "Community Outreach",
    teamIds: ["team-002"],
    assignmentCount: 7,
    workload: 91,
    availability: "In Meeting",
  },
  {
    id: "mem-003",
    name: "Sarah Chen",
    email: "sarah.chen@hopebridge.org",
    role: "Coordinator",
    department: "Community Outreach",
    teamIds: ["team-002"],
    assignmentCount: 6,
    workload: 88,
    availability: "Available",
  },
  {
    id: "mem-004",
    name: "James Okonkwo",
    email: "james.okonkwo@hopebridge.org",
    role: "Team Lead",
    department: "Fundraising & Partnerships",
    teamIds: ["team-003"],
    assignmentCount: 4,
    workload: 68,
    availability: "Remote",
  },
  {
    id: "mem-005",
    name: "Priya Sharma",
    email: "priya.sharma@hopebridge.org",
    role: "Finance",
    department: "Finance & Compliance",
    teamIds: ["team-005"],
    assignmentCount: 3,
    workload: 62,
    availability: "Available",
  },
  {
    id: "mem-006",
    name: "Elena Vasquez",
    email: "elena.vasquez@hopebridge.org",
    role: "Operations Manager",
    department: "Operations",
    teamIds: ["team-004"],
    assignmentCount: 5,
    workload: 74,
    availability: "Focused",
  },
  {
    id: "mem-007",
    name: "Marcus Wright",
    email: "marcus.wright@hopebridge.org",
    role: "Executive Director",
    department: "Leadership",
    teamIds: ["team-006"],
    assignmentCount: 2,
    workload: 45,
    availability: "Available",
  },
  {
    id: "mem-008",
    name: "Aisha Rahman",
    email: "aisha.rahman@hopebridge.org",
    role: "Field Staff",
    department: "Community Outreach",
    teamIds: ["team-002"],
    assignmentCount: 4,
    workload: 72,
    availability: "Remote",
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-001",
    name: "Programs & Impact",
    department: "Programs & Impact",
    description: "Designs and delivers HopeBridge program strategy and measurable impact.",
    leadId: "mem-001",
    leadName: "Maya Patel",
    memberIds: ["mem-001"],
    status: "Active",
    capacity: 76,
    defaultPermission: "Program Manager",
    nextDeadline: "2026-08-25",
  },
  {
    id: "team-002",
    name: "Community Outreach",
    department: "Community Outreach",
    description: "Coordinates field operations and community engagement initiatives.",
    leadId: "mem-002",
    leadName: "Daniel Brooks",
    secondaryLeadId: "mem-003",
    secondaryLeadName: "Sarah Chen",
    memberIds: ["mem-002", "mem-003", "mem-008"],
    status: "Active",
    capacity: 91,
    defaultPermission: "Team Lead",
    nextDeadline: "2026-08-22",
  },
  {
    id: "team-003",
    name: "Fundraising & Partnerships",
    department: "Fundraising & Partnerships",
    description: "Manages donor relationships, grants, and strategic partnerships.",
    leadId: "mem-004",
    leadName: "James Okonkwo",
    memberIds: ["mem-004"],
    status: "Active",
    capacity: 68,
    defaultPermission: "Team Lead",
    nextDeadline: "2026-08-28",
  },
  {
    id: "team-004",
    name: "Operations",
    department: "Operations",
    description: "Supports internal coordination, logistics, and daily foundation operations.",
    leadId: "mem-006",
    leadName: "Elena Vasquez",
    memberIds: ["mem-006"],
    status: "Active",
    capacity: 74,
    defaultPermission: "Team Lead",
    nextDeadline: "2026-08-24",
  },
  {
    id: "team-005",
    name: "Finance & Compliance",
    department: "Finance & Compliance",
    description: "Oversees financial stewardship, reporting, and regulatory compliance.",
    leadId: "mem-005",
    leadName: "Priya Sharma",
    memberIds: ["mem-005"],
    status: "Active",
    capacity: 62,
    defaultPermission: "Finance",
    nextDeadline: "2026-08-30",
  },
  {
    id: "team-006",
    name: "Leadership",
    department: "Leadership",
    description: "Executive leadership and cross-department strategic alignment.",
    leadId: "mem-007",
    leadName: "Marcus Wright",
    memberIds: ["mem-007"],
    status: "Active",
    capacity: 45,
    defaultPermission: "Executive Director",
    nextDeadline: "2026-09-02",
  },
];

export const INITIAL_ASSIGNMENTS: TeamAssignment[] = [
  {
    id: "asg-001",
    title: "Q3 Impact Metrics Review",
    ownerId: "mem-001",
    ownerName: "Maya Patel",
    teamId: "team-001",
    teamName: "Programs & Impact",
    priority: "High",
    dueDate: "2026-08-25",
    status: "In Progress",
  },
  {
    id: "asg-002",
    title: "Food Distribution Coordination",
    ownerId: "mem-003",
    ownerName: "Sarah Chen",
    teamId: "team-002",
    teamName: "Community Outreach",
    priority: "Critical",
    dueDate: "2026-08-22",
    status: "In Progress",
  },
  {
    id: "asg-003",
    title: "Grant Proposal Draft — Riverside",
    ownerId: "mem-004",
    ownerName: "James Okonkwo",
    teamId: "team-003",
    teamName: "Fundraising & Partnerships",
    priority: "Medium",
    dueDate: "2026-08-28",
    status: "To Do",
  },
  {
    id: "asg-004",
    title: "August Beneficiary Follow-Up Review",
    ownerId: "mem-002",
    ownerName: "Daniel Brooks",
    teamId: "team-002",
    teamName: "Community Outreach",
    priority: "High",
    dueDate: "2026-08-20",
    status: "Completed",
  },
  {
    id: "asg-005",
    title: "Vendor Contract Renewal",
    ownerId: "mem-006",
    ownerName: "Elena Vasquez",
    teamId: "team-004",
    teamName: "Operations",
    priority: "Medium",
    dueDate: "2026-08-24",
    status: "In Review",
  },
];

export const INITIAL_DISCUSSIONS: TeamDiscussion[] = [
  {
    id: "disc-001",
    title: "Q3 Community Outreach Planning",
    teamId: "team-002",
    teamName: "Community Outreach",
    participantIds: ["mem-002", "mem-003", "mem-008"],
    lastMessage: "Let's finalize the distribution schedule by Thursday.",
    lastActivityAt: "2026-08-21T11:18:00",
    unreadCount: 2,
    resolved: false,
    messages: [
      {
        id: "msg-001",
        authorId: "mem-002",
        authorName: "Daniel Brooks",
        body: "Team — we need to align on Q3 outreach priorities before the field schedule is locked.",
        createdAt: "2026-08-21T09:30:00",
      },
      {
        id: "msg-002",
        authorId: "mem-003",
        authorName: "Sarah Chen",
        body: "I've drafted the distribution zones. @Daniel Brooks can you review the capacity assumptions?",
        createdAt: "2026-08-21T10:45:00",
      },
      {
        id: "msg-003",
        authorId: "mem-002",
        authorName: "Daniel Brooks",
        body: "Let's finalize the distribution schedule by Thursday.",
        createdAt: "2026-08-21T11:18:00",
      },
    ],
  },
  {
    id: "disc-002",
    title: "Program KPI Alignment",
    teamId: "team-001",
    teamName: "Programs & Impact",
    participantIds: ["mem-001"],
    lastMessage: "Maya shared the updated impact framework for review.",
    lastActivityAt: "2026-08-20T16:20:00",
    unreadCount: 0,
    resolved: true,
    messages: [
      {
        id: "msg-004",
        authorId: "mem-001",
        authorName: "Maya Patel",
        body: "Maya shared the updated impact framework for review.",
        createdAt: "2026-08-20T16:20:00",
      },
    ],
  },
];

export const INITIAL_MEETINGS: TeamMeeting[] = [
  {
    id: "mtg-001",
    title: "Programs Weekly Sync",
    teamId: "team-001",
    teamName: "Programs & Impact",
    date: "2026-08-21",
    time: "2:00 PM",
    attendeeIds: ["mem-001"],
    agenda: "Review Q3 milestones, assignment backlog, and capacity planning.",
    completed: false,
  },
  {
    id: "mtg-002",
    title: "Fundraising Review",
    teamId: "team-003",
    teamName: "Fundraising & Partnerships",
    date: "2026-08-22",
    time: "10:30 AM",
    attendeeIds: ["mem-004"],
    agenda: "Pipeline review, grant deadlines, and partner follow-ups.",
    completed: false,
  },
  {
    id: "mtg-003",
    title: "Community Outreach Planning",
    teamId: "team-002",
    teamName: "Community Outreach",
    date: "2026-08-23",
    time: "1:00 PM",
    attendeeIds: ["mem-002", "mem-003", "mem-008"],
    agenda: "Field schedule, volunteer coordination, and resource allocation.",
    completed: false,
  },
];

export const INITIAL_ACTIVITY: TeamActivityEvent[] = [
  {
    id: "act-001",
    type: "member_added",
    detail: "Maya added Daniel to Programs & Impact",
    teamId: "team-001",
    createdAt: "2026-08-21T11:12:00",
  },
  {
    id: "act-002",
    type: "assignment_created",
    detail: 'Community Outreach assigned "Food Distribution Coordination" to Sarah',
    teamId: "team-002",
    createdAt: "2026-08-21T10:28:00",
  },
  {
    id: "act-003",
    type: "meeting_scheduled",
    detail: "Operations scheduled Weekly Coordination Meeting",
    teamId: "team-004",
    createdAt: "2026-08-21T09:15:00",
  },
  {
    id: "act-004",
    type: "assignment_completed",
    detail: 'Daniel completed "August beneficiary follow-up review"',
    teamId: "team-002",
    createdAt: "2026-08-21T08:00:00",
  },
  {
    id: "act-005",
    type: "lead_updated",
    detail: "Finance & Compliance added Priya as Team Lead",
    teamId: "team-005",
    createdAt: "2026-08-20T17:30:00",
  },
];
